### ISSUE TITLE
add description and link to GitHub repo

### ISSUE THREAD

**Issue by 251** [klee/klee.github.io#110]
There is no link to https://klee.github.io/ on the main page of this repository.

**Comment by ccadar** [comment]
Do you mean in `README.md`?

**Comment by 251** [comment]
No, in the settings of this repo. Basically replace: "No description, website, or topics provided." on the top by clicking "edit".

**Comment by ccadar** [comment]
I see.  I added a description, is it ok?

**Comment by 251** [comment]
Much more comfortable, thanks.
