### ISSUE TITLE
LLVM 2.9 build instructions have very out of date dependencies

### ISSUE THREAD

**Issue by delcypher** [klee/klee.github.io#12]
Building doesn't require ``dejagnu`` or ``subversion`` any more.

We now need cmake, git and python.

**Comment by andreamattavelli** [comment]
@delcypher I believe that we already fixed this issue. Moreover, we are moving the documentation towards LLVM 3.4. Thus, I would close this issue if you agree.

**Comment by delcypher** [comment]
@andreamattavelli Sure. Let's close this.
