### ISSUE TITLE
Restructure documentation/tutorials

### ISSUE THREAD

**Issue by 251** [klee/klee.github.io#148]
I looked at the "intro box" issue but couldn't come up with a sufficient solution. We should think about re-structuring the page. I'd suggest to merge tutorials and documentation and use different sections on a single page (development, installation, usage, ...).

**Comment by ccadar** [comment]
@251 I would love to see a better web page for KLEE.  I think the structure is somewhat chaotic right now.  I'm also happy to chat in person about restructuring the page if you prefer.

**Comment by ccadar** [comment]
Let's close this, I think #242 does this to a large extent.
