### ISSUE TITLE
incorrect markdown in developer's guide

### ISSUE THREAD

**Issue by Smattr** [klee/klee.github.io#202]
When looking at the [Developer's Guide](http://klee.github.io/docs/developers-guide/) I came across an issue that seems to stem from some incorrect markdown:

<img width="855" alt="Screen Shot 2019-11-24 at 15 33 57" src="https://user-images.githubusercontent.com/203893/69503587-06e6d900-0ed0-11ea-8c42-870cc9f9b7b2.png">

As visible in the attachment:
* there's a stray `</tt>` in the text
* the final word is not rendered as a link because the bracketing is back to front

Please let me know if it's unclear what I'm referring to here.

**Comment by ccadar** [comment]
Thanks for reporting these issues, can you submit a PR fixing them?

**Comment by Smattr** [comment]
Sure, can do. However, I need to do some paperwork for my employer first to get their approval for personal contributions like this so it might take a little while.

**Comment by ccadar** [comment]
Thanks, @Smattr .  We'd be happy to have your contributions.  But if it's difficult to get approval, we'll try to fix these small issues ourselves.

**Comment by Smattr** [comment]
Thanks! However, I think 5f443bdfd1af9b8a521e980dbf823f66bd5daf99 does not fix the text that's not rendered as a link at the end of the paragraph. I.e. the second bullet point in the original post.
