### ISSUE TITLE
Developer's Guide page is inaccurate.

### ISSUE THREAD

**Issue by ocelaiwo** [klee/klee.github.io#212]
In the "Miscellaneous" section, "Writing messages to standard error" subsection, the guide suggests to look at `lib/Core/Common.h` file, which does not exist in the codebase. Also, in the same section, in "Adding a command line option to a tool" subsection, the guide suggests to look at `lib/core/Executor.cpp`, which should probably be `lib/Core/Executor.cpp`

**Comment by ccadar** [comment]
Thanks for reporting this.  A PR fixing this would be appreciated.  The new file is `include/klee/Internal/Support/ErrorHandling.h` (and yes, `core` should be `Core`).
