### ISSUE TITLE
Update documentation to assume LLVM 3.4

### ISSUE THREAD

**Issue by ccadar** [klee/klee.github.io#24]
Our documentation including tutorials, etc. assumes LLVM 2.9 is used.  Since now LLVM 3.4 is the recommended version, we should update the documentation accordingly.

**Comment by ccadar** [comment]
Tutorials have been updated in https://github.com/klee/klee.github.io/pull/34, with the exception of Coreutils, which needs to be done too.

**Comment by andreamattavelli** [comment]
@ccadar I was wondering how to modify the Coreutils tutorial. For example, do we want to describe the compilation step with whole-program-llvm?

**Comment by andreamattavelli** [comment]
Done with the commit 923f4f1.
