### ISSUE TITLE
Update LLVM 2.9 documentation to install newer version of STP

### ISSUE THREAD

**Issue by andreamattavelli** [klee/klee.github.io#28]
The current documentation suggests to install STP 2.1.0 for compiling KLEE on LLVM 2.9. For LLVM 3.4, instead, the documentation suggests to use the STP version from the master branch on git (currently 2.1.2).
Is there any reason for this? That is, is there any known bug for KLEE on LLVM 2.9 and STP 2.1.2?
I'm asking this because I've observed that STP 2.1.2 has better performances.

**Comment by ccadar** [comment]
There is no reason for this discrepancy, and we should resolve it.  I propose to recommend users to use STP 2.1.2, and also mention how to try the latest STP.

**Comment by andreamattavelli** [comment]
I am to uniform the two build pages (2.9 and 3.4) in the case of STP. I would thus rather modify the page to use the upstream version (as it is now for 3.4).
If we want we might modify both pages to point to STP 2.1.2.

**Comment by ccadar** [comment]
Great, looking forward to this consolidated page.  I propose to choose one STP version that we have tried in the past (say 2.1.2 for now) and also mention how to obtain the latest one.

**Comment by andreamattavelli** [comment]
Closing, since we modified the web page.
