### ISSUE TITLE
Update developer documentation to reference up-to-date doxygen 

### ISSUE THREAD

**Issue by MartinNowack** [klee/klee.github.io#29]
From the KLEE mailing list: Marko Dimjašević

https://klee.github.io/docs/developers-guide/
there's a link in the Building code documentation section leading to:
http://test.minormatter.com/~ddunbar/klee-doxygen/index.html
When I follow that link, I get a "Server not found" error.

**Comment by andreamattavelli** [comment]
Doxygen link in the main page points to @delcypher's home page: https://www.doc.ic.ac.uk/~dsl11/klee-doxygen
We should find a way to update it to every new commit, in a way similar to what happens with the docker image.

**Comment by ccadar** [comment]
Closing this, as we now have #296
