### ISSUE TITLE
Doxygen link on page footer is dead (duplicate of #29 but that one is dead)

### ISSUE THREAD

**Issue by Jerald** [klee/klee.github.io#296]
It's happened again! #29 should definitely have been closed years back, so this isn't exactly a duplicate.

The [current doxygen link in the page footer](http://www.doc.ic.ac.uk/~dsl11/klee-doxygen/) (the same one as was recommended in #29 5 years ago) is now 404ing. Not sure who's managing it now, but I figured this might be the best place to start.

**Comment by ccadar** [comment]
Thanks for reporting this.  Ideally, we would set up a script that uploads the current Doxygen documentation to a website on every push.  However, a simpler thing to do would be to publish the Doxygen documentation on every release; given that it doesn't change that often, this would be enough, I think.

**Comment by sophiastr** [comment]
i want to deal with this issue.
I am interested in contributing to the project you are developing.
Do you still need help?

**Comment by ccadar** [comment]
Yes, we do, please see https://github.com/klee/klee.github.io/issues/309

**Comment by 251** [comment]
Fixed via #318.
