### ISSUE TITLE
Build STP command is not correct

### ISSUE THREAD

**Issue by andreamattavelli** [klee/klee.github.io#36]
To build STP it is necessary to build Minisat, however the following command is not correct:

```
$ cmake -DSTATICCOMPILE=ON -DCMAKE_INSTALL_PREFIX=/usr/ ../
```

In fact, `-DSTATICCOMPILE=ON` is valid only in CryptoMinisat. We should think if we want to move to CryptoMinisat or remove the extra argument.

**Comment by ccadar** [comment]
This was fixed in #68
