### ISSUE TITLE
Klee build instructions for x64 should include installation of tcmalloc

### ISSUE THREAD

**Issue by naegling** [klee/klee.github.io#41]
Following the current build instructions on 64 bit linux results in a klee that terminates all states when memory use exceeds 2G. Since the default memory threshold is 2000 MB, that leaves a very narrow 48K window to avoid the error. The solution (as documented elsewhere here) is to use tcmalloc. Mentioning that in the build instructions would have saved me several days of troubleshooting :)

**Comment by andreamattavelli** [comment]
Fixed issue with PR #42.
