### ISSUE TITLE
Revise tutorial 1 and 2 documentation

### ISSUE THREAD

**Issue by marikgoldstein** [klee/klee.github.io#45]
Hi KLEE,

I was struggling a little with the introductory documentation (tutorials 1 and 2) because I was expecting clang to generate an .o object file. The tutorial asks to run clang and then to run klee.o

@andreamattavelli helped me to realize that the .bc files (a format with which I was confused) were really the ones to run klee on.

The tutorial mentions clang and then suggests:
klee get_sign.o

This might leave someone confused and looking for an object file.

Thanks!

**Comment by andreamattavelli** [comment]
Addressed in PR #46
