### ISSUE TITLE
Keep documentation for old KLEE versions

### ISSUE THREAD

**Issue by ccadar** [klee/klee.github.io#69]
We should keep the documentation, particularly the build instructions, for old KLEE versions.

**Comment by delcypher** [comment]
We should probably have a release page that lists the releases and links to them and the documentation for them.

IIRC Jekyll allows a way for some files to go through without processing so we could build the docs for the old versions and put them in the repo and serve them directly.

**Comment by ccadar** [comment]
@delcypher , I agree.  Do you have perhaps some cycles to draft a skeleton (e.g., do it for one version to understand what you mean exactly)?  Thanks.

**Comment by delcypher** [comment]
This is now done for v.1.3.0. I've not generated the docs for the older versions.

**Comment by delcypher** [comment]
@ccadar Note that the release documentation is a little complicated. It is documented in the `README.md` file.

**Comment by andreamattavelli** [comment]
As a side note, I believe that generating the old documentation is a little bit tricky, in the sense that it is not immediate to find the corresponding commit. For example, the current documentation for version 1.3.0 is not correct: it contains the refactoring of `pc->kquery` which is not part of 1.3.0, but only of the master.

**Comment by delcypher** [comment]
@andreamattavelli I agree it is quite tricky.

So what I've done (just now) is to create a `v1.3.0` branch that contains the state of the tree used to generate the `v1.3.0` documentation (commited to master in the generated form in 884a25eaca7510ca96bba9085ad71990afdada4e ).

In order to fix the `v1.3.0` documentation we should apply fixes to that branch (e.g. revert relevant commits) and once we are happy generate the documentation again and then commit the generated code to the `master` branch.

Make sense?

In the future we should create branches for all KLEE releases.

**Comment by andreamattavelli** [comment]
@delcypher it absolutely does.

**Comment by andreamattavelli** [comment]
@delcypher after a painful search, I believe that the branch `v1.3.0` is now in sync with KLEE/1.3.0

**Comment by andreamattavelli** [comment]
@ccadar creating a version for previous releases is trickier than expected. For example, some updates that were applied recently are valid also for previous releases (e.g., updated instructions for coreutils with LLVM 3.4). We should decide a strategy for keeping/discarding commits.

**Comment by delcypher** [comment]
@andreamattavelli Okay. Now what you'll have to do is regenerate the `v.1.3.0` documentation as html and then push those generated files into the right place in https://github.com/klee/klee.github.io/tree/master/releases/docs

**Comment by andreamattavelli** [comment]
@delcypher Yes, as soon as I have half an hour free. I'd like to avoid to create a mess.

**Comment by delcypher** [comment]
@andreamattavelli Updating release documentation is incredibly painful. I would in general recommend only creating release documentation once at the same time as release and then have that documentation frozen.

**Comment by andreamattavelli** [comment]
@delcypher It is, but now we now have to cope with the need to preserve old, outdated docs. We should decide what's the strategy. There are two possible ways in my opinion:

1. the drastic way: we revert all commits before a given KLEE release;
2. the soft (painful) way: we try to retro-fit all changes that are potentially helpful for a given KLEE release.
