### ISSUE TITLE
Dead link to Google's libgtest

### ISSUE THREAD

**Issue by mpdehnel** [klee/klee.github.io#70]
I built KLEE this morning from scratch and when following the process found that one of the links is dead.

http://klee.github.io/build-llvm34/ — "Build instructions with LLVM 3.4".

>05 (Optional) Build libgtest:
>…
>`$ curl -OL https://googletest.googlecode.com/files/gtest-1.7.0.zip`

This URL no longer works. 
I believe the correct URL (and please note the new file name) is https://github.com/google/googletest/archive/release-1.7.0.zip 

Different versions / releases including the latest 1.8.0 (with which I did not attempt to build KLEE) can be found here: https://github.com/google/googletest/releases

All the rest of the process worked perfectly.

Thanks!

**Comment by andreamattavelli** [comment]
Closed via #71
