### ISSUE TITLE
sandbox.tgz link broke

### ISSUE THREAD

**Issue by Mic92** [klee/klee.github.io#82]
I try to reproduce the OSDI experiments: http://klee.github.io/docs/coreutils-experiments/
Unfortunately the link to the sandbox is no longer available: http://www.doc.ic.ac.uk/~cristic/klee/klee-cu-sandbox.html

Is there an alternative source?

Thanks in advance.

**Comment by Mic92** [comment]
fixed by the pull request.

**Comment by andreamattavelli** [comment]
@Mic92 it seems that it works correctly. Try to whitelist the website since it relies on javascript.

**Comment by Mic92** [comment]
yes you were right.
